export const products = [
  {
    _id: '1',
    name: 'Sheep',
    image: '/images/sheep.png',
    description: 'Both Mutton and Wool yielding sheep available at affordable prices.',
    price: 100.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
    reviews: [
      {
        _id: 'r1',
        name: 'John Doe',
        rating: 5,
        comment: 'Great quality wool!',
        createdAt: '2025-01-10',
      },
      {
        _id: 'r2',
        name: 'Jane Smith',
        rating: 4,
        comment: 'Very tasty meat.',
        createdAt: '2025-01-12',
      },
    ],
  },
  {
    _id: '2',
    name: 'Cattle',
    image: '/images/cattle.png',
    description: 'Well breeded cows amd bulls available for sale.',
    price: 599.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
    reviews: [
      {
        _id: 'r3',
        name: 'Alice Johnson',
        rating: 5,
        comment: 'Good quality milk!',
        createdAt: '2025-01-14',
      },
      {
        _id: 'r4',
        name: 'Bob Brown',
        rating: 3,
        comment: 'Overpriced, but the meat is good.',
        createdAt: '2025-01-15',
      },
    ],
  },
  {
    _id: '3',
    name: 'Chicken',
    image: '/images/chicken.png',
    description: 'Broilers and Layers available.',
    price: 29.99,
    countInStock: 5,
    rating: 4.8,
    numReviews: 15,
    reviews: [
      {
        _id: 'r5',
        name: 'Chris Green',
        rating: 5,
        comment: 'Great quality eggs!',
        createdAt: '2025-01-08',
      },
      {
        _id: 'r6',
        name: 'Dana White',
        rating: 4,
        comment: 'Love the meat from the roosters.',
        createdAt: '2025-01-11',
      },
    ],
  },
  {
    _id: '4',
    name: 'Pigs',
    image: '/images/pigs.png',
    description: 'Fat and ready to slaughter pigs available.',
    price: 699.99,
    countInStock: 3,
    rating: 4.7,
    numReviews: 9,
    reviews: [
      {
        _id: 'r7',
        name: 'Emily Davis',
        rating: 5,
        comment: 'Great quality pork!',
        createdAt: '2025-01-07',
      },
      {
        _id: 'r8',
        name: 'Frank Hall',
        rating: 4,
        comment: 'A bit expensive but worth the investment.',
        createdAt: '2025-01-13',
      },
    ],
  },
  {
    _id: '5',
    name: 'Goats',
    image: '/images/goats.png',
    description: 'Goats with good quality mutton.',
    price: 49.99,
    countInStock: 15,
    rating: 4.3,
    numReviews: 20,
    reviews: [
      {
        _id: 'r9',
        name: 'Grace Martin',
        rating: 4,
        comment: 'Good quality meat.',
        createdAt: '2025-01-09',
      },
      {
        _id: 'r10',
        name: 'Henry Wilson',
        rating: 5,
        comment: 'Great breed quality!',
        createdAt: '2025-01-16',
      },
    ],
  },
  {
    _id: '6',
    name: 'Ducks',
    image: '/images/ducks.png',
    description: 'Can provide eggs and can be kept as pets.',
    price: 99.99,
    countInStock: 8,
    rating: 4.6,
    numReviews: 18,
    reviews: [
      {
        _id: 'r11',
        name: 'Ivy Thomas',
        rating: 5,
        comment: 'Cute Duckies!!!',
        createdAt: '2025-01-06',
      },
      {
        _id: 'r12',
        name: 'Jack Lee',
        rating: 4,
        comment: 'Love the meat on them.',
        createdAt: '2025-01-17',
      },
    ],
  },
];

export default products;
